import React from 'react';

interface PageProps {
  onShowMain: () => void;
}

const DisclaimerPage: React.FC<PageProps> = ({ onShowMain }) => {
  return (
    <div className="w-full max-w-3xl mx-auto animate-fade-in mt-8">
      <div className="w-full bg-gray-800/50 backdrop-blur-sm border border-gray-700 rounded-xl shadow-2xl p-6 md:p-8">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-3xl font-bold text-white">Disclaimer</h2>
          <button
            onClick={onShowMain}
            className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors text-sm font-semibold flex items-center gap-2"
            aria-label="Back to article generator"
          >
             <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
               <path fillRule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clipRule="evenodd" />
             </svg>
            Back to Generator
          </button>
        </div>
        <div className="prose prose-invert max-w-none text-gray-300 leading-relaxed space-y-4">
            <p>
                The information and content provided by the Gosai AI Blog Article Generator (the "Service") is for general informational purposes only. All content generated by the Service is created by an artificial intelligence model and is provided on an "as is" basis.
            </p>
            <h3 className="text-indigo-400">No Guarantees of Accuracy</h3>
            <p>
                While we strive to provide high-quality and accurate information, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any content generated by the Service. The AI model may produce information that is inaccurate, incomplete, or outdated.
            </p>
            <h3 className="text-indigo-400">User Responsibility</h3>
            <p>
                You are solely responsible for fact-checking, reviewing, and editing any content generated by the Service before publication or use. Any reliance you place on such information is strictly at your own risk. We strongly recommend that you verify any factual claims, data, or statistics from reliable primary sources.
            </p>
            <h3 className="text-indigo-400">Limitation of Liability</h3>
            <p>
                Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Service or reliance on any information provided by the Service. Your use of the Service and your reliance on any generated content is solely at your own risk.
            </p>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerPage;
